### ISSUE TITLE
panic: sql: Register called twice for driver sqlite3

### ISSUE THREAD

**Issue by FireTiger23** [logoove/sqlite#1]
在goframe中使用会报错：
panic: sql: Register called twice for driver sqlite3

goroutine 1 [running]:
database/sql.Register({0x7ff6894d1a64, 0x7}, {0x7ff689bd7b00, 0xc0002cb160})
        C:/Program Files/Go/src/database/sql/sql.go:51 +0x1e5
github.com/mattn/go-sqlite3.init.0()
        C:/Users/FireTiger/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.10/sqlite3.go:237 +0x89

**Comment by logoove** [comment]
goframe是2.0么 看看这个https://gitee.com/yoby/go

**Comment by logoove** [comment]
已经更新了2.0兼容
