### ISSUE TITLE
goframe中要如何使用？

### ISSUE THREAD

**Issue by FireTiger23** [logoove/sqlite#2]
readme中提到的
goframe中只需在boot 下面go文件里面加上 _ github.com/logoove/sqlite即可在orm使用,不需要任何其他修改
有没有具体的例子或步骤？
cannot find database driver for specified database type "sqlite", did you misspell type name "sqlite" or forget importing the database driver?

**Comment by logoove** [comment]
你是goframe2.0m吗这个我还没有试过 1.16的话有例子https://gitee.com/yoby/go 里面是个采集项目用的sqlite3

**Comment by logoove** [comment]
goframe2.0经过测试也是直接支持的需要在manifeat/config/config.yaml配置database: 下`default:
    type: "sqlite"
    link: "./resource/db.db"`就可以了
在internel/cmd/cmd.go 中加入`_ "github.com/logoove/sqlite"`就可以使用的.例子
`id, _ := g.Model("user").Data(g.Map{"name": "john", "age": 1}).InsertAndGetId()`插入一条数据并获取id

**Comment by logoove** [comment]
1.16中你需要在配置中toml或yaml等中database里面 type: "sqlite"和 link: "./resource/db.db"两个配置正确,其它地方和mysql操作一致

**Comment by logoove** [comment]
更新了一下,有各个不同版本例子在里面,自己在go1.17下测试过是可以用的,2.0新增加sqlite驱动,1.17以下不需要专门写驱动
